### ISSUE TITLE
Add tests and document new feature: reading configuration from file

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-js#1243]
With #1241, Honeybadger can be configured from a file, such as `honeybadger.config.js`.

**Note: this is only available for Honeybadger running on the server.**

## TODO
- [x] Tests for reading config from file
- [x] Tests for configuration precedence: config file, constructor parameters, default values
- [x] Documentation for configuration file - https://github.com/honeybadger-io/docs/issues/375
